<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Demo</title>
</head>

<body>
    <!-- <h1>
        <?php echo get_class($this) ?>
    </h1> -->
    <div>
        <?php echo $this->setTemplate("code/messages.phtml");?>
        <?php echo $this->getChildHtml('messages') ?>
        <?php echo $this->getChildHtml('header') ?>
        <?php echo $this->getChildHtml('footer') ?>
        <?php echo $this->getChildHtml('head') ?>
        <?php echo $this->getChildHtml('content') ?>
    </div>
</body>

</html>