<div class="container">
    <div class="form">
        <h2>Customer Forgot Password</h2>
        <form method="POST" action="<?php echo $this->getUrl('customer/account/forgotpassword') ?>">
            <div class="row">
                <div>
                    <label for="customer_email">Email:</label>
                    <input type="text" value="" name="customer[customer_email]" id="customer_email">
                </div>
            </div>
            <div>
                <input type="submit" name="submit" value="Submit">
            </div>
        </form>
        <p>Already have an acoount? <a href="<?php echo $this->getUrl('customer/account/login') ?>">click here</a></p>
    </div>
</div>