<div class="container">
    <div class="form">
        <h2>Customer Login</h2>
        <form method="POST" action="<?php echo $this->getUrl('customer/account/login') ?>">
            <div class="row">
                <div>
                    <label for="customer_email">Email:</label>
                    <input type="text" value="" name="customer[customer_email]" id="customer_email">
                </div>
                <div>
                    <label for="password">Password:</label>
                    <input type="password" value="" name="customer[password]" id="password">
                </div>
            </div>
            <div>
                <input type="submit" name="submit" value="Submit">
            </div>
        </form>
        <p>Forgot your password? <a href="<?php echo $this->getUrl('customer/account/forgotpassword') ?>">click here</a>
        <p>Don't have an acoount? <a href="<?php echo $this->getUrl('customer/account/register') ?>">click here</a></p>
        </p>
    </div>
</div>