<footer>
    <div>
        <div class="footerSection-1">
            <div class="footerItem">
                <p class="footerHeading">About Us</p>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit</p>
                <p>Secure Online Payments</p>
            </div>
            <div class="footerItem">
                <p class="footerHeading">Categories</p>
                <ul>
                    <li><a href="#">Clothing</a></li>
                    <li><a href="#">Lingrie</a></li>
                    <li><a href="#">Footwear</a></li>
                    <li><a href="#">Hand bag</a></li>
                    <li><a href="#">Jwellery</a></li>
                    <li><a href="#">Belt</a></li>
                </ul>
            </div>
            <div class="footerItem">
                <p class="footerHeading">Informations</p>
                <ul>
                    <li><a href="#">About Us</a></li>
                    <li><a href="#">Contact Us</a></li>
                    <li><a href="#">Term & Condition</a></li>
                    <li><a href="#">Return & Exchange</a></li>
                    <li><a href="#">Shipping & Delivery</a></li>
                    <li><a href="#">Privacy Policy</a></li>
                </ul>
            </div>
            <div class="footerItem">
                <p class="footerHeading">Contact Us</p>
            </div>
        </div>
        <div class="footerSection-2">
            <p>Copyright &#169; 2024 All rights reserved and made with &#9829; by Ecommerce Project</p>
        </div>
    </div>

</footer>