<!-- <header class="header">
    <div class="logo">Project</div>
    <nav class="nav">
        <a href="#">Home</a>
        <a href="#">About</a>
        <a href="#">Services</a>
        <a href="#">Contact</a>
    </nav>
</header> -->
<header class="header">
    <div class="logo">
        <img src="" alt="Online Marketplace Logo">
    </div>
    <nav class="nav">
        <a href="#">Home</a>
        <a href="#">About</a>
        <a href="#">Services</a>
        <a href="#">Contact</a>
    </nav>
</header>



