<!DOCTYPE html>
<html lang="en">

<head>
    <title>Project</title>
    <?php echo ($this->getChildHtml('head')) ?>
</head>

<body>
    <style>
        body {
            margin: 0;
        }
    </style>
    <div>
        <!-- <div>
            <?php echo ($this->getChildHtml('messages')) ?>
        </div> -->
        <div>
            <?php echo ($this->getChildHtml('header')) ?>
        </div>
        <div>
            <?php echo ($this->getChildHtml('content')) ?>
        </div>
        <div>
            <?php echo ($this->getChildHtml('footer')) ?>
        </div>
    </div>
</body>

</html>