<?php
   $productCollection =  Mage::getModel('catalog/product')->getCollection();
//    echo get_class($productCollection);
?>
<div class="product-list">
    <h2>Product List</h2>
    <table>
        <thead>
            <tr>
                <th>Name</th>
                <th>SKU</th>
                <th>Color</th>
                <th>Size</th>
                <th>Description</th>
                <th>Price</th>
                <th>Status</th>
                <th colspan="2">Action</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($productCollection->getData() as $product) : ?>
                <tr>
                    <td><?php echo $product->getName(); ?></td>
                    <td><?php echo $product->getSku(); ?></td>
                    <td><?php echo $product->getColor(); ?></td>
                    <td><?php echo $product->getSize(); ?></td>
                    <td><?php echo $product->getDescription(); ?></td>
                    <td><?php echo $product->getPrice(); ?></td>
                    <td><?php echo $product->getStatus(); ?></td>
                    <td><a
                            href="<?php echo $this->getUrl("admin/catalog_product/delete?product_id={$product->getId()}") ?>">Delete</a>
                    </td>
                    <td><a
                            href="<?php echo $this->getUrl("admin/catalog_product/form?product_id={$product->getId()}") ?>">Update</a>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>
