<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Demo</title>
</head>

<body>
    <div>
        <?php echo ($this->setTemplate('core/messages.phtml')) ?>
        <?php echo ($this->getChild('messages')->toHtml()) ?>
        <?php echo ($this->getChild('head')->toHtml()) ?>
        <?php echo ($this->getChild('header')->toHtml()) ?>
        <?php echo ($this->getChild('content')->toHtml()) ?>
        <?php echo ($this->getChild('left')->toHtml()) ?>
        <?php echo ($this->getChild('footer')->toHtml()) ?>
    </div>
</body>

</html>