<?php
$data = $this->getCategory();
echo "<script>var status = '{$data->getStatus()}'</script>";
?>

<div class="form">
    <h2>Category Form</h2>
    <form method="POST" action="<?php echo $this->getUrl('admin/catalog_category/save') ?>">
        <div>
            <input type="hidden" value="<?php echo $data->getCategoryId() ?>" name="catalog_category[category_id]">
        </div>
        <div class="row">
            <div>
                <label for="name">Category Name:</label>
                <input type="text" value="<?php echo $data->getCategoryName() ?>" name="catalog_category[category_name]"
                    id="name">
            </div>
            <!-- <div>
                <label for="status">Category Status:</label>
                <input type="text" value="<?php echo $data->getStatus() ?>" name="catalog_category[status]" id="status">
            </div> -->
            <div class="row">
                <label for="status">Status:</label>
                <select name="catalog_category[status]" id="status">
                    <option value="enable" <?php echo ($data->getStatus() === 'enable') ? 'selected' : ''; ?>>Enable
                    </option>
                    <option value="disable" <?php echo ($data->getStatus() === 'disable') ? 'selected' : ''; ?>>Disable
                    </option>
                </select>
            </div>
        </div>
        <div>
            <input type="submit" name="submit" value="Submit">
        </div>
    </form>
</div>