<?php
$categoryModel = Mage::getModel("catalog/category")->getCollection();
?>

<div class="list">
    <h2>Category List</h2>
    <table>
        <thead>
            <tr>
                <th>Name</th>
                <th>Status</th>
                <th colspan="2">Action</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($categoryModel->getData() as $_category): ?>
                <tr>
                    <td>
                        <?php echo $_category->getCategoryName() ?>
                    </td>
                    <td>
                        <?php echo $_category->getStatus() ?>
                    </td>
                    <td><a
                            href="<?php echo $this->getUrl("admin/catalog_category/delete?category_id={$_category->getId()}") ?>">Delete</a>
                    </td>
                    <td><a
                            href="<?php echo $this->getUrl("admin/catalog_category/form?category_id={$_category->getId()}") ?>">Update</a>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>